### ISSUE TITLE
oscar#oscar-cp_2.11;4.0.0-SNAPSHOT: not found

### ISSUE THREAD

**Issue by ydl-super** [svissicchio/Repetita#10]
Hello, I have the following problems when I am reproducing this project. Is it no longer maintained due to the long time? Do you have any good solutions to solve my problems？

(*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: oscar#oscar-cp_2.11;4.0.0-SNAPSHOT: not found
(*:update) sbt.ResolveException: unresolved dependency: oscar#oscar-cp_2.11;4.0.0-SNAPSHOT: not found

info] Resolving jline#jline;2.12 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: oscar#oscar-cp_2.11;4.0.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          oscar:oscar-cp_2.11:4.0.0-SNAPSHOT (C:\Users\win\Desktop\TE\Repetita\build.sbt#L10)
[warn]            +- repetita:repetita_2.11:0.1-SNAPSHOT
[info] Resolving org.scala-sbt#api;0.13.15 ...

**Comment by svissicchio** [comment]
Hi, sorry for the slow response. As you probably guessed, the problem was a broken dependency to the external repository for the oscar CP library. Pierre Schaus has fixed the problem with the oscar repository -- thank you very much, Pierre! So, the current version of Repetita (pushed minutes ago) should not raise the exception anymore: I double-checked this is the case on a fresh clone of the updated repository.

**Comment by ydl-super** [comment]
Hi,Thank you very much for having solved my problem.
